# Generated by Django 5.1.6 on 2025-03-18 06:58

import django.core.validators
import resumes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), resumes.models.validate_pdf_size]),
        ),
    ]
